Controllers/paketAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webÖdev.Models;

namespace webÖdev.Controllers
{
    public class paketAdminController : Controller
    {
        private paketlerEntities1 db = new paketlerEntities1();

        // GET: paketAdmin
        public ActionResult Index()
        {
            var pakets = db.pakets.Include(p => p.fiyatlar);
            return View(pakets.ToList());
        }

        // GET: paketAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket paket = db.pakets.Find(id);
            if (paket == null)
            {
                return HttpNotFound();
            }
            return View(paket);
        }

        // GET: paketAdmin/Create
        public ActionResult Create()
        {
            ViewBag.mevsimID = new SelectList(db.fiyatlars, "mevsimID", "gider1");
            return View();
        }

        // POST: paketAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mevsimID,gun1,gun2,gun3,gun4,gun5,gun6,gun7,gun8,gun9,gun10")] paket paket)
        {
            if (ModelState.IsValid)
            {
                db.pakets.Add(paket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.mevsimID = new SelectList(db.fiyatlars, "mevsimID", "gider1", paket.mevsimID);
            return View(paket);
        }

        // GET: paketAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket paket = db.pakets.Find(id);
            if (paket == null)
            {
                return HttpNotFound();
            }
            ViewBag.mevsimID = new SelectList(db.fiyatlars, "mevsimID", "gider1", paket.mevsimID);
            return View(paket);
        }

        // POST: paketAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "mevsimID,gun1,gun2,gun3,gun4,gun5,gun6,gun7,gun8,gun9,gun10")] paket paket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.mevsimID = new SelectList(db.fiyatlars, "mevsimID", "gider1", paket.mevsimID);
            return View(paket);
        }

        // GET: paketAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket paket = db.pakets.Find(id);
            if (paket == null)
            {
                return HttpNotFound();
            }
            return View(paket);
        }

        // POST: paketAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            paket paket = db.pakets.Find(id);
            db.pakets.Remove(paket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/paketAdmin/Create.cshtml
@model webÖdev.Models.paket

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Yeni Paket Oluştur</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>


                </ul>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>paket</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.mevsimID, "mevsimID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("mevsimID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.mevsimID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun4, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun4, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun4, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun5, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun5, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun5, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun6, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun6, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun6, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun7, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun7, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun7, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun8, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun8, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun8, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun9, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun9, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun9, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun10, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun10, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun10, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

        <div>
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>


</body>
</html>

Views/paketAdmin/Delete.cshtml
@model webÖdev.Models.paket

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Paket Sil</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>

                </ul>
            </div>
        </div>
    </div>

    <h3>Silmek istediğinize emin misiniz?</h3>
    <div>
        <h4>paket</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.gun1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun3)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun3)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun4)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun4)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun5)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun5)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun6)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun6)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun7)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun7)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun8)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun8)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun9)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun9)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun10)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun10)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fiyatlar.gider1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fiyatlar.gider1)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
        }
    </div>

</body>
</html>

Views/paketAdmin/Details.cshtml
@model webÖdev.Models.paket


@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Detaylar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>


                </ul>
            </div>
        </div>
    </div>

    <div>
        <h4>paket</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.gun1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun3)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun3)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun4)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun4)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun5)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun5)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun6)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun6)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun7)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun7)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun8)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun8)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun9)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun9)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gun10)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gun10)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fiyatlar.gider1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fiyatlar.gider1)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Düzenle", "Edit", new { id = Model.mevsimID }) |
        @Html.ActionLink("Listeye Geri Dön", "Index")
    </p>

</body>
</html>

Views/paketAdmin/Edit.cshtml
@model webÖdev.Models.paket

@{
    ViewBag.Title = "Edit";
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Düzenle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>paket</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.mevsimID)

            <div class="form-group">
                @Html.LabelFor(model => model.gun1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun4, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun4, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun4, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun5, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun5, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun5, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun6, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun6, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun6, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun7, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun7, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun7, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun8, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun8, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun8, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun9, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun9, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun9, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gun10, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.gun10, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.gun10, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index")
    </div>

</body>
</html>

Views/paketAdmin/Index.cshtml
@model IEnumerable<webÖdev.Models.paket>

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Paketler</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>

<p>
    @Html.ActionLink("Yeni Paket Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.gun1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun5)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun6)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun7)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun8)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun9)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gun10)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fiyatlar.gider1)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.gun1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun5)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun6)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun7)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun8)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun9)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gun10)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fiyatlar.gider1)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.mevsimID }) |
                @Html.ActionLink("Detaylar", "Details", new { id = item.mevsimID }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.mevsimID })
            </td>
        </tr>
    }

</table>
  </body>
</html>