Controllers/adminKullaniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webÖdev.Models;

namespace webÖdev.Controllers
{
    public class adminKullaniciController : Controller
    {
        private kullaniciEntities db = new kullaniciEntities();

        // GET: adminKullanici
        public ActionResult Index()
        {
            return View(db.tblKullanicis.ToList());
        }

        // GET: adminKullanici/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKullanici tblKullanici = db.tblKullanicis.Find(id);
            if (tblKullanici == null)
            {
                return HttpNotFound();
            }
            return View(tblKullanici);
        }

        // GET: adminKullanici/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: adminKullanici/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Kadi,Adi,Soyadi,Eposta,Sifre")] tblKullanici tblKullanici)
        {
            if (ModelState.IsValid)
            {
                db.tblKullanicis.Add(tblKullanici);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblKullanici);
        }

        // GET: adminKullanici/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKullanici tblKullanici = db.tblKullanicis.Find(id);
            if (tblKullanici == null)
            {
                return HttpNotFound();
            }
            return View(tblKullanici);
        }

        // POST: adminKullanici/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Kadi,Adi,Soyadi,Eposta,Sifre")] tblKullanici tblKullanici)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblKullanici).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblKullanici);
        }

        // GET: adminKullanici/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKullanici tblKullanici = db.tblKullanicis.Find(id);
            if (tblKullanici == null)
            {
                return HttpNotFound();
            }
            return View(tblKullanici);
        }

        // POST: adminKullanici/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblKullanici tblKullanici = db.tblKullanicis.Find(id);
            db.tblKullanicis.Remove(tblKullanici);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/adminKullanici/Create.cshtml
@model webÖdev.Models.tblKullanici

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Kadi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Kadi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Kadi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index")
    </div>
</body>
</html>

Views/adminKullanici/Delete.cshtml
@model webÖdev.Models.tblKullanici

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>
    <h3>Silmek istediğine emin misin ?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Kadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Soyadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Soyadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Eposta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Eposta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sifre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sifre)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-default" /> |
                @Html.ActionLink("Listeye Geri Dön", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/adminKullanici/Details.cshtml
@model webÖdev.Models.tblKullanici

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Kadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Soyadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Soyadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Eposta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Eposta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sifre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sifre)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Düzenle", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Listeye Geri Dön", "Index")
    </p>
</body>
</html>

Views/adminKullanici/Edit.cshtml
@model webÖdev.Models.tblKullanici

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.Kadi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Kadi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Kadi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index")
    </div>
</body>
</html>

Views/adminKullanici/Index.cshtml
@model IEnumerable<webÖdev.Models.tblKullanici>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>

                </ul>
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Yeni Kullanıcı Ekle", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Kadi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Soyadi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Eposta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sifre)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Kadi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Soyadi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Eposta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sifre)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Detaylar", "Details", new { id = item.id }) |
                    @Html.ActionLink("Sil", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
</body>
</html>