Controllers/adminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webÖdev.Controllers
{
    public class adminHomeController : Controller
    {
        // GET: adminHome
        public ActionResult adminAnaSayfa()
        {
            return View();
        }
    }
}

Views/adminHome/adminAnaSayfa.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "adminAnaSayfa", "adminHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "adminAnaSayfa", "adminHome")</li>
                    <li>@Html.ActionLink("Paketler", "Index", "paketAdmin")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "Index", "adminKullanici")</li>
                </ul>
            </div>
        </div>
    </div>

    <h2>Hazır Paketler</h2>

   
</body>
</html>