Models/paket_eng.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webÖdev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paket_eng
    {
        public int mevsimID { get; set; }
        public string day1 { get; set; }
        public string day2 { get; set; }
        public string day3 { get; set; }
        public string day4 { get; set; }
        public string day5 { get; set; }
        public string day6 { get; set; }
        public string day7 { get; set; }
        public string day8 { get; set; }
        public string day9 { get; set; }
        public string day10 { get; set; }
    
        public virtual fiyatlar_eng fiyatlar_eng { get; set; }
    }
}

Controllers/paket_engController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webÖdev.Models;

namespace webÖdev.Controllers
{
    public class paket_engController : Controller
    {
        private paketler_engEntities1 db = new paketler_engEntities1();

        // GET: paket_eng
        public ActionResult Index()
        {
            var paket_eng = db.paket_eng.Include(p => p.fiyatlar_eng);
            return View(paket_eng.ToList());
        }
        public ActionResult kullaniciPaket_eng()
        {
            var paket_eng = db.paket_eng.Include(p => p.fiyatlar_eng);
            return View(paket_eng.ToList());
        }

        // GET: paket_eng/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket_eng paket_eng = db.paket_eng.Find(id);
            if (paket_eng == null)
            {
                return HttpNotFound();
            }
            return View(paket_eng);
        }
        public ActionResult kullaniciDetails_eng(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket_eng paket_eng = db.paket_eng.Find(id);
            if (paket_eng == null)
            {
                ViewBag.title = "HAta ";
                return HttpNotFound();
            }
            return View(paket_eng);
        }

        // GET: paket_eng/Create
        public ActionResult Create()
        {
            ViewBag.mevsimID = new SelectList(db.fiyatlar_eng, "mevsimID", "expence1");
            return View();
        }

        // POST: paket_eng/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mevsimID,day1,day2,day3,day4,day5,day6,day7,day8,day9,day10")] paket_eng paket_eng)
        {
            if (ModelState.IsValid)
            {
                db.paket_eng.Add(paket_eng);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.mevsimID = new SelectList(db.fiyatlar_eng, "mevsimID", "expence1", paket_eng.mevsimID);
            return View(paket_eng);
        }

        // GET: paket_eng/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket_eng paket_eng = db.paket_eng.Find(id);
            if (paket_eng == null)
            {
                return HttpNotFound();
            }
            ViewBag.mevsimID = new SelectList(db.fiyatlar_eng, "mevsimID", "expence1", paket_eng.mevsimID);
            return View(paket_eng);
        }

        // POST: paket_eng/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "mevsimID,day1,day2,day3,day4,day5,day6,day7,day8,day9,day10")] paket_eng paket_eng)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paket_eng).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.mevsimID = new SelectList(db.fiyatlar_eng, "mevsimID", "expence1", paket_eng.mevsimID);
            return View(paket_eng);
        }

        // GET: paket_eng/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paket_eng paket_eng = db.paket_eng.Find(id);
            if (paket_eng == null)
            {
                return HttpNotFound();
            }
            return View(paket_eng);
        }

        // POST: paket_eng/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            paket_eng paket_eng = db.paket_eng.Find(id);
            db.paket_eng.Remove(paket_eng);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/paket_eng/Details.cshtml
@model webÖdev.Models.paket_eng

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "giris_eng", "anaSayfa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "giris_eng", "anaSayfa")</li>
                    <li>@Html.ActionLink("Packets", "Index", "paket_eng")</li>
                    <li>@Html.ActionLink("Contact", "defaultIletisim_eng", "Page")</li>
                    <li>@Html.ActionLink("Sign Up", "Index", "uyeOl_eng.aspx")</li>
                    <li>@Html.ActionLink("Sign In", "Index", "KullaniciGirisi_eng.aspx")</li>
                </ul>
            </div>
        </div>
    </div>
        <div>
            <h4>paket_eng</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.day1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day2)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day3)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day3)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day4)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day4)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day5)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day5)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day6)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day6)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day7)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day7)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day8)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day8)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day9)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day9)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.day10)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.day10)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence2)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence2)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence3)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence3)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence4)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence4)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence5)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence5)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence6)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence6)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence7)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence7)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence8)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence8)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence9)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence9)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.fiyatlar_eng.expence10)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fiyatlar_eng.expence10)
                </dd>
            </dl>
        </div>
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
</body>
</html>

Views/paket_eng/Index.cshtml
@model IEnumerable<webÖdev.Models.paket_eng>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "giris_eng", "anaSayfa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "giris_eng", "anaSayfa")</li>
                    <li>@Html.ActionLink("Packets", "Index", "paket_eng")</li>
                    <li>@Html.ActionLink("Contact", "defaultIletisim_eng", "Page")</li>
                    <li>@Html.ActionLink("Sign Up", "Index", "uyeOl_eng.aspx")</li>
                    <li>@Html.ActionLink("Sign In", "Index", "KullaniciGirisi_eng.aspx")</li>
                </ul>
            </div>
        </div>
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.day1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day9)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day10)
            </th>
            
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.day1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day10)
                </td>
                
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.mevsimID }) |
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence10)
                </td>
            </tr>
        }

    </table>
</body>
</html>

Views/paket_eng/kullaniciDetails_eng.cshtml
@model IEnumerable<webÖdev.Models.paket_eng>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Hazır Paketler</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "Index_eng", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index_eng", "Home")</li>
                    <li>@Html.ActionLink("Packets", "kullaniciPaket_eng", "paket_eng")</li>
                    <li>@Html.ActionLink("Create Package", "Index", "paketSecimi_eng.aspx")</li>
                    <li>@Html.ActionLink("Contact", "Index_eng", "Page")</li>
                </ul>
            </div>
        </div>
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.day1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day9)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence9)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day10)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence10)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.day1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day10)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence1)
                </td>
                <td>
                    @Html.ActionLink("Details", "kullaniciDetails_eng", new { id = item.mevsimID }) |
                </td>
            </tr>
        }

    </table>
</body>
</html>

Views/paket_eng/kullaniciPaket_eng.cshtml
@model IEnumerable<webÖdev.Models.paket_eng>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UAF TRAVEL", "Index_eng", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index_eng", "Home")</li>
                    <li>@Html.ActionLink("Packets", "kullaniciPaket_eng", "paket_eng")</li>
                    <li>@Html.ActionLink("Create Package", "Index", "paketSecimi_eng.aspx")</li>
                    <li>@Html.ActionLink("Contact", "Index_eng", "Page")</li>
                </ul>
            </div>
        </div>
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.day1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day6)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day7)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day8)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day9)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.day10)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.fiyatlar_eng.expence1)
            </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.day1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.day10)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fiyatlar_eng.expence10)
                </td>
            </tr>
        }

        </table>
</body>
</html>